In [2]:
import matplotlib.pyplot as plt
import tensorflow as tf
import tensorflow.keras

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D , MaxPool2D , Flatten , Dropout 
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.optimizers import Adam

from sklearn.metrics import classification_report,confusion_matrix
from sklearn.model_selection import train_test_split

import cv2
import PIL
import os

import numpy as np
import random

In [3]:
# Load the model

import glob

model = ['best_model.h5']

blocked = glob.glob('dataset/Blocked/*.*')
free = glob.glob('dataset/Free/*.*')

model = tf.keras.models.load_model('best_model.h5')

In [4]:
# Preprocessing

labels = []
f = []
b = []

for i in blocked:   
    image = tf.keras.preprocessing.image.load_img(i, color_mode='rgb', target_size = (224,224))
    image = np.array(image)
    b.append(image)
    labels.append(0)
for i in free:   
    image = tf.keras.preprocessing.image.load_img(i, color_mode='rgb', target_size = (224,224))
    image = np.array(image)
    f.append(image)
    labels.append(1)
    
b = np.array(b)
f = np.array(f)
labels = np.array(labels)

<PIL.Image.Image image mode=RGB size=224x224 at 0x7F0BFA264E48>
[[[193 179 170]
  [180 166 155]
  [181 167 158]
  ...
  [170 194 240]
  [169 193 241]
  [184 211 255]]

 [[187 173 162]
  [192 179 170]
  [185 171 162]
  ...
  [180 204 250]
  [177 201 249]
  [154 178 224]]

 [[188 173 166]
  [186 172 163]
  [187 172 165]
  ...
  [175 198 242]
  [161 183 230]
  [167 189 238]]

 ...

 [[250 241 200]
  [255 241 200]
  [253 240 198]
  ...
  [124 154 192]
  [153 185 223]
  [143 178 218]]

 [[255 255 239]
  [255 255 239]
  [255 255 246]
  ...
  [133 166 201]
  [151 186 226]
  [155 190 230]]

 [[255 255 255]
  [255 255 255]
  [255 255 253]
  ...
  [156 195 236]
  [155 192 234]
  [170 209 250]]]
<PIL.Image.Image image mode=RGB size=224x224 at 0x7F0BFA264E48>
[[[193 201 186]
  [197 203 189]
  [195 203 188]
  ...
  [ 45  51  67]
  [ 62  71  86]
  [ 64  74  86]]

 [[198 206 193]
  [196 204 191]
  [198 206 193]
  ...
  [ 40  46  62]
  [ 56  64  75]
  [ 57  60  75]]

 [[195 203 188]
  [194 202 187]
  

<PIL.Image.Image image mode=RGB size=224x224 at 0x7F0BFA264E48>
[[[250 246 235]
  [249 247 234]
  [239 237 224]
  ...
  [ 62  76  85]
  [ 89  99  98]
  [ 78  87  84]]

 [[252 248 236]
  [249 245 234]
  [232 228 216]
  ...
  [ 83  95  95]
  [ 97 107 108]
  [132 145 136]]

 [[252 248 237]
  [252 248 237]
  [233 230 215]
  ...
  [ 56  71  78]
  [ 62  77  82]
  [ 80  94  95]]

 ...

 [[197 189 176]
  [198 188 176]
  [195 188 172]
  ...
  [ 69  96 105]
  [ 63  83  92]
  [108 132 136]]

 [[194 184 172]
  [197 187 175]
  [194 187 171]
  ...
  [ 77 102 109]
  [ 61  81  90]
  [ 72  97 102]]

 [[191 183 170]
  [193 186 170]
  [193 187 171]
  ...
  [ 67  87  94]
  [ 76 104 108]
  [ 81 108 115]]]


KeyboardInterrupt: 

In [23]:
# Get confidence if the way is blocked

for image in f:
    
    image = np.asarray(image).astype('float32').reshape((-1,224,224,3))
    prob_blocked = model.predict(image)         
               
    print("Free dataset, blocked confidence: {}".format(np.round(prob_blocked[0][0],2)))

print('\n')
    
for image in b:
    
    image = np.asarray(image).astype('float32').reshape((-1,224,224,3))
    prob_blocked = model.predict(image)
               
    print("Blocked dataset, blocked confidence: {}".format(np.round(prob_blocked[0][0],2)))

Free dataset, blocked confidence: 0.0
Free dataset, blocked confidence: 0.0
Free dataset, blocked confidence: 0.0
Free dataset, blocked confidence: 0.0
Free dataset, blocked confidence: 0.0
Free dataset, blocked confidence: 0.0
Free dataset, blocked confidence: 0.0
Free dataset, blocked confidence: 0.0
Free dataset, blocked confidence: 0.0
Free dataset, blocked confidence: 0.0
Free dataset, blocked confidence: 0.0
Free dataset, blocked confidence: 0.0
Free dataset, blocked confidence: 0.0
Free dataset, blocked confidence: 0.0
Free dataset, blocked confidence: 0.0
Free dataset, blocked confidence: 0.0
Free dataset, blocked confidence: 0.0
Free dataset, blocked confidence: 0.0
Free dataset, blocked confidence: 0.0
Free dataset, blocked confidence: 0.0
Free dataset, blocked confidence: 0.0
Free dataset, blocked confidence: 0.0
Free dataset, blocked confidence: 0.3700000047683716
Free dataset, blocked confidence: 0.0
Free dataset, blocked confidence: 0.0
Free dataset, blocked confidence: 0

In [14]:
all_camera_idx_available = []

for camera_idx in range(10):
    cap = cv2.VideoCapture(camera_idx)
    if cap.isOpened():
        print(f'Camera index available: {camera_idx}')
        all_camera_idx_available.append(camera_idx)
        cap.release()

Camera index available: 0
Camera index available: 2


In [ ]:
cap = cv2.VideoCapture(2)

def wait(delay):
    framecount = 0
    # capture and discard frames while the delay is not over
    while framecount < delay:
        cap.read()
        framecount += 1

while True:
    delay = 1
    wait(delay)
    # get and display next frame
    ret, img = cap.read()
    cv2.imshow("Image", img)
    if cv2.waitKey(1) & 0xFF == ord('q'):
            break

cv2.destroyAllWindows()